### PR TITLE
docs(.circleci):CircleCi config docs

### LINKED ISSUE #37: Need docs for circle Ci configuration
The docs should cover the following things:
1. What the config is doing.
2. When the builds can fail and how to fix them.

### PR DESCRIPTION
**Pull request by piyushagwl007**
Fixes:#37

### CODE REVIEW

**Comment by piyushagwl007** [comment]
Preview of doc file.

Ignore the grey cursor.

image

**Review by nimish-gupta — CHANGES_REQUESTED** [review]
Deployment?

**Comment by piyushagwl007** [comment]
> Deployment?

@nimish-gupta We have not added deployment through the circle CI yet. We will update the docs once we add deployment through circle CI. :smiley:

**Comment by piyushagwl007** [comment]
@karansapolia @nihalanisumit can you guys review this P.R.?

**Review by nimish-gupta — APPROVED** [review]

**Review by karansapolia — APPROVED** [review]
All related docs should be incrementally updated now that we have call-to-actions in the PR checklist to update docs. LGTM for now.

**Review by nihalanisumit — APPROVED** [review]
LGTM!

**Pull request merged**
